# Generated by Django 4.2.9 on 2024-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='start_date',
            field=models.DateField(),
        ),
    ]
