# Generated by Django 4.2.9 on 2024-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_loandata_end_date_alter_loandata_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='interest_rate',
            field=models.FloatField(),
        ),
    ]
